### ISSUE TITLE
Adding a disclamer for arduino

### ISSUE THREAD

**Issue by drenghel** [tonton81/Circular_Buffer#4]
Hi,  
your work looks very nice & all, I was about to use it on a regular Qt C++ project and I didn't noticed it was littered with `Serial.print`, not that it's bad, but obviously it prevents it's use outside of Arduino.
And I haven't seen soon enough the `arduino` tag.

Bottom line, maybe add a warning on your Readme.md, to prevent other ppl to fall for it again 😄 

Cheers !

**Comment by tonton81** [comment]
thanks for the heads up. If it’s usuable outside arduino I will add defines for the Serial print functions to only exist in the arduino environment, but you’ll lose the function when used outside the arduino environment. It’s for the queue display buffer, not really needed but it helped debug the queue system when it was developed. Only the list() function uses prints. Can you try deleting that function in your copy and remove it from the header?
